"use strict";
exports.__esModule = true;
var casino_1 = require("./casino");
var player_1 = require("./player");
var blackjack_1 = require("./blackjack");
var roulette_1 = require("./roulette");
var playerOne = new player_1.Player("Luz", "Niz", "luzniz37@gmail.com", "Luce375");
var playerTwo = new player_1.Player("Valentin", "Lopez", "valenlopez@gmail.com", "185Valen");
var casinoOne = new casino_1.Casino("Vegas", "Las Vegas", "Sant Marino 386");
var rouletteOne = new roulette_1.Roulette(500, 15, 36);
var blackjackVIP = new blackjack_1.Blackjack(5000, 3, 54, 1);
casinoOne.setNewUser(playerOne);
casinoOne.setNewUser(playerTwo);
console.log(casinoOne.getPlayers());
console.log(casinoOne.getUserConected());
playerOne.signIn("luzniz37@gmail.com", "Luce375");
console.log(casinoOne.getUserConected());
console.table(casinoOne.getPlayers());
//playerTwo.signIn("valenlopez@gmail.com", "185Valen");
console.log(casinoOne.getUserConected());
casinoOne.buyTokens(2000, playerOne);
console.log(playerOne.getTokens());
console.log(rouletteOne.spinRoulette());
console.log(blackjackVIP.dealCards());
console.log(blackjackVIP.dealCards());
