"use strict";
exports.__esModule = true;
var spider_1 = require("./spider");
var animalList_1 = require("./animalList");
var cat_1 = require("./cat");
var fish_1 = require("./fish");
var animalList = new animalList_1.AnimalList();
var ara01 = new spider_1.Spider(8);
var michiOne = new cat_1.Cat("Michi", 4);
var nemo01 = new fish_1.Fish("Nemo", 0);
animalList.addAnimal(ara01);
animalList.addAnimal(michiOne);
animalList.addAnimal(nemo01);
console.log(animalList.showInfo());
ara01.eat();
michiOne.eat();
nemo01.eat();
ara01.walk(8);
michiOne.walk(4);
nemo01.walk(0);
michiOne.play("Michi");
nemo01.play("Nemo");
animalList.search(ara01);
animalList.deleteAnimal(ara01);
console.log(animalList.showInfo());
