"use strict";
exports.__esModule = true;
var phone_1 = require("./phone");
var phoneWithCamera_1 = require("./phoneWithCamera");
var phoneWithRadio_1 = require("./phoneWithRadio");
var contact_1 = require("./contact");
//const contacts: Contact[] = [];
var telUno = new phoneWithCamera_1.PhoneWithCamera();
var telDos = new phoneWithRadio_1.PhoneWithRadio();
console.log(telUno instanceof phone_1.Phone);
console.log(telUno instanceof phoneWithCamera_1.PhoneWithCamera);
console.log(telUno instanceof phoneWithRadio_1.PhoneWithRadio);
console.log(telDos instanceof phone_1.Phone);
console.log(telDos instanceof phoneWithRadio_1.PhoneWithRadio);
console.log(telDos instanceof phoneWithCamera_1.PhoneWithCamera);
telUno.newContact(new contact_1.Contact("Luz", "Niz", 2224445837));
console.log(telUno.getContacts());
telUno.sendMessage("Hola Mundo", "Luz", "Niz");
telUno.makeCall("Luz", "Niz");
