"use strict";
exports.__esModule = true;
var autoCiudad_1 = require("./autoCiudad");
var autoDeportivo_1 = require("./autoDeportivo");
var camioneta_1 = require("./camioneta");
var autoCiudad = new autoCiudad_1.AutoCiudad("Fiat", "F320", 2020);
var autoDeportivo = new autoDeportivo_1.AutoDeportivo("Ferrari", "F456", 2022);
var camioneta = new camioneta_1.Camioneta("Renault", "Pick Up", 2021);
console.log(autoCiudad.showInfo());
console.log(autoDeportivo.showInfo());
console.log(camioneta.showInfo());
autoCiudad.prender();
autoDeportivo.prender();
camioneta.prender();
autoCiudad.acelerar();
autoDeportivo.acelerar();
camioneta.acelerar();
console.log(autoCiudad.getVelocidadActual());
console.log(autoDeportivo.getVelocidadActual());
console.log(camioneta.getVelocidadActual());
